import type { ServiceVerticalPack } from "@/verticals/types";

export const beautyVerticalPack: ServiceVerticalPack = {
  id: "beauty",
  version: "v0.1",
  displayName: "美容／护理服务",
  shortName: "美容",
  mode: "appointment",
  subjectKind: "person",
  labels: {
    customer: "顾客",
    customers: "顾客",
    subject: "顾客",
    subjects: "顾客",
    resource: "美容师／房间",
    resources: "美容师／房间",
    booking: "预约",
    bookings: "预约",
    staff: "门店职员",
    venue: "门店",
  },
  subjectFields: [
    { key: "preference", label: "服务偏好", required: false, kind: "textarea", administrativeOnly: true },
  ],
  services: [
    { id: "beauty_facial", name: "面部护理", durationMin: 90, category: "facial" },
    { id: "beauty_body", name: "身体护理", durationMin: 90, category: "body" },
    { id: "beauty_nail", name: "美甲", durationMin: 90, category: "nail" },
    { id: "beauty_consult", name: "服务咨询", durationMin: 30, category: "consult" },
  ],
  faqTemplates: [
    {
      id: "beauty_hours",
      category: "opening_hours",
      question: "几点营业？",
      answer: "营业时间与可预约时段以门店核准设定为准。",
      keywords: ["几点开", "营业时间", "收几点", "星期日"],
      channels: ["whatsapp", "web", "phone"],
      enabled: true,
      administrativeOnly: true,
    },
    {
      id: "beauty_booking",
      category: "booking_policy",
      question: "点样预约？",
      answer: "可以告诉我想做的服务和偏好日期／时段，我会查询目前可预约时间。",
      keywords: ["预约", "有冇位", "想约", "book"],
      channels: ["whatsapp", "web"],
      enabled: true,
      administrativeOnly: true,
    },
    {
      id: "beauty_price",
      category: "payment",
      question: "几钱？",
      answer: "收费只会按门店已核准价目表回答；需要顾问确认的方案会转交门店职员。",
      keywords: ["几钱", "价钱", "收费", "价格", "package"],
      channels: ["whatsapp", "web", "phone"],
      enabled: true,
      administrativeOnly: true,
    },
  ],
  escalationKeywords: ["呼吸困难", "大量流血", "严重过敏", "晕倒", "失去反应"],
  restrictedQuestionPatterns: [
    /是不是.*过敏/u,
    /係咪.*敏感/u,
    /要不要.*吃药/u,
    /要唔要.*食药/u,
    /应该.*治疗/u,
    /可唔可以.*药/u,
  ],
  followUpRules: [
    {
      id: "beauty_30d",
      label: "30 日护理提醒",
      trigger: "time_since_service",
      afterDays: 30,
      serviceIds: ["beauty_facial", "beauty_body"],
      customerMessage: "如果你想安排下一次护理，可以直接在这里查看可预约时间。",
    },
  ],
  integrationTargets: [],
  defaultHumanApprovalLeadHours: 12,
  metadata: {
    candidate: true,
    notes: ["仅验证预约型服务行业复用能力。", "涉及健康、过敏、治疗判断的问题全部转人工。"],
  },
};
