import type { ServiceVerticalPack } from "@/verticals/types";

export const dentalVerticalPack: ServiceVerticalPack = {
  id: "dental",
  version: "v0.1",
  displayName: "牙科诊所",
  shortName: "牙科",
  mode: "appointment",
  subjectKind: "person",
  labels: {
    customer: "病人",
    customers: "病人",
    subject: "病人",
    subjects: "病人",
    resource: "医生／诊室",
    resources: "医生／诊室",
    booking: "预约",
    bookings: "预约",
    staff: "诊所职员",
    venue: "诊所",
  },
  subjectFields: [],
  services: [
    { id: "svc_check", name: "口腔检查", durationMin: 30, category: "checkup" },
    { id: "svc_scaling", name: "洗牙／洁治", durationMin: 45, category: "cleaning" },
    { id: "svc_filling", name: "补牙", durationMin: 60, category: "treatment" },
    { id: "svc_root", name: "根管治疗", durationMin: 90, category: "treatment", requiresHumanConfirmation: true },
    { id: "svc_ortho", name: "矫齿覆诊", durationMin: 30, category: "followup" },
  ],
  faqTemplates: [
    {
      id: "faq_hours",
      category: "opening_hours",
      question: "你哋几点开门？",
      answer: "诊所营业时间以诊所已核准设定为准；实际可预约时间请以系统显示为准。",
      keywords: ["几点开", "营业时间", "开门", "收几点", "星期日", "星期六"],
      channels: ["whatsapp", "web", "phone"],
      enabled: true,
      administrativeOnly: true,
    },
    {
      id: "faq_location",
      category: "location",
      question: "诊所喺边？",
      answer: "地址与交通方式以诊所已核准资料为准。",
      keywords: ["喺边", "地址", "点去", "位置", "地铁", "交通"],
      channels: ["whatsapp", "web", "phone"],
      enabled: true,
      administrativeOnly: true,
    },
    {
      id: "faq_reschedule",
      category: "booking_policy",
      question: "点样改期？",
      answer: "可以直接提出改期，系统会先查询可用时段；接近应诊时间的改动会转交诊所职员确认。",
      keywords: ["改期", "改时间", "转时间", "换日子", "改预约"],
      channels: ["whatsapp", "web"],
      enabled: true,
      administrativeOnly: true,
    },
    {
      id: "faq_cancel",
      category: "booking_policy",
      question: "可以取消预约吗？",
      answer: "可以提出取消预约。系统会先核对预约，再按诊所规则处理；接近应诊时间的取消可能需要职员确认。",
      keywords: ["取消", "唔去", "不去", "取消预约"],
      channels: ["whatsapp", "web"],
      enabled: true,
      administrativeOnly: true,
    },
    {
      id: "faq_voucher",
      category: "voucher",
      question: "收唔收医疗券？",
      answer: "是否接受医疗券以诊所核准设定为准；系统不会自行推断。",
      keywords: ["医疗券", "长者医疗券", "医券"],
      channels: ["whatsapp", "web", "phone"],
      enabled: true,
      administrativeOnly: true,
    },
    {
      id: "faq_insurance",
      category: "insurance",
      question: "可唔可以用保险？",
      answer: "保险安排视乎诊所与个别计划。你可以留下保险公司或计划名称，由前台确认保障与手续。",
      keywords: ["保险", "claim", "索偿", "索赔"],
      channels: ["whatsapp", "web", "phone"],
      enabled: true,
      administrativeOnly: true,
    },
  ],
  escalationKeywords: ["流血不止", "面肿", "剧痛", "发烧", "呼吸困难", "撞甩牙", "整晚痛"],
  restrictedQuestionPatterns: [
    /係咪.*病/u,
    /是不是.*病/u,
    /要唔要.*食药/u,
    /要不要.*吃药/u,
    /应该.*治疗/u,
    /点医/u,
    /怎么治/u,
    /需唔需要.*拔/u,
    /需不需要.*拔/u,
  ],
  followUpRules: [
    {
      id: "dental_scaling_6m",
      label: "6 个月洗牙召回",
      trigger: "time_since_service",
      afterMonths: 6,
      serviceIds: ["svc_scaling"],
      customerMessage: "距离上次洁治已约半年，如需要可以在这里安排下一次预约。",
    },
    {
      id: "dental_scaling_12m",
      label: "12 个月洗牙召回",
      trigger: "time_since_service",
      afterMonths: 12,
      serviceIds: ["svc_scaling"],
      customerMessage: "距离上次洁治已约一年，如需要可以在这里安排下一次预约。",
    },
  ],
  integrationTargets: [
    {
      id: "hkda-dcms",
      displayName: "HKDA DCMS",
      kind: "cms",
      status: "candidate",
      desiredCapabilities: ["booking.read", "booking.write", "availability.read", "customer.lookup", "followup.read"],
      verifiedCapabilities: [],
      noteZhHk: "等待真实接口、正式文档或客户现场验证；未验证前不得宣称已整合。",
    },
    {
      id: "dentoease",
      displayName: "DentoEase",
      kind: "cms",
      status: "candidate",
      desiredCapabilities: ["booking.read", "booking.write", "availability.read", "customer.lookup", "followup.read"],
      verifiedCapabilities: [],
      noteZhHk: "第一阶段不假设内部 API；优先使用获授权接口或日历桥接。",
    },
    {
      id: "clinicsolution-dental",
      displayName: "ClinicSolution Dental",
      kind: "cms",
      status: "candidate",
      desiredCapabilities: ["booking.read", "booking.write", "availability.read", "customer.lookup"],
      verifiedCapabilities: [],
      noteZhHk: "待真实客户版本与接口确认后再实现专用适配器。",
    },
  ],
  defaultHumanApprovalLeadHours: 24,
  metadata: {
    candidate: false,
    notes: ["Clinic Flow 当前生产方向的第一个垂直行业包。", "医疗判断、治疗建议、临床分诊仍不属于 Agent 权限。"],
  },
};
