import type { ServiceVerticalPack } from "@/verticals/types";

export const petCareVerticalPack: ServiceVerticalPack = {
  id: "pet-care",
  version: "v0.1",
  displayName: "宠物美容／寄养",
  shortName: "宠物服务",
  mode: "appointment",
  subjectKind: "pet",
  labels: {
    customer: "宠物主人",
    customers: "宠物主人",
    subject: "宠物",
    subjects: "宠物",
    resource: "美容师／寄养位",
    resources: "美容师／寄养位",
    booking: "预约",
    bookings: "预约",
    staff: "店员",
    venue: "门店",
  },
  subjectFields: [
    { key: "pet_name", label: "宠物名字", required: true, kind: "text", administrativeOnly: true },
    { key: "species", label: "种类", required: true, kind: "select", options: ["狗", "猫", "其他"], administrativeOnly: true },
    { key: "breed", label: "品种", required: false, kind: "text", administrativeOnly: true },
    { key: "size", label: "体型", required: false, kind: "select", options: ["小型", "中型", "大型"], administrativeOnly: true },
    { key: "handling_notes", label: "接待备注", required: false, kind: "textarea", administrativeOnly: true },
  ],
  services: [
    { id: "pet_bath", name: "洗澡护理", durationMin: 60, category: "grooming" },
    { id: "pet_full_groom", name: "全套美容", durationMin: 120, category: "grooming" },
    { id: "pet_nail", name: "剪甲护理", durationMin: 30, category: "grooming" },
    { id: "pet_boarding_day", name: "日间寄养", durationMin: 480, category: "boarding", requiresHumanConfirmation: true },
    { id: "pet_boarding_night", name: "过夜寄养", category: "boarding", requiresHumanConfirmation: true },
  ],
  faqTemplates: [
    {
      id: "pet_hours",
      category: "opening_hours",
      question: "几点开门？",
      answer: "营业时间以门店已核准设定为准；可预约时段请以系统显示为准。",
      keywords: ["几点开", "营业时间", "开门", "收几点"],
      channels: ["whatsapp", "web", "phone"],
      enabled: true,
      administrativeOnly: true,
    },
    {
      id: "pet_groom_booking",
      category: "booking_policy",
      question: "点样预约美容？",
      answer: "可以直接告诉我宠物名字、想做的服务和偏好日期，我会先查询可用时段。",
      keywords: ["美容预约", "剪毛", "冲凉", "洗澡", "预约美容", "有冇位"],
      channels: ["whatsapp", "web"],
      enabled: true,
      administrativeOnly: true,
    },
    {
      id: "pet_boarding_items",
      category: "preparation",
      question: "寄养要带咩？",
      answer: "寄养所需物品与接收条件以门店已核准清单为准；系统会显示门店当前要求，不自行判断宠物健康资格。",
      keywords: ["寄养带咩", "寄养准备", "要带什么", "过夜寄养"],
      channels: ["whatsapp", "web", "phone"],
      enabled: true,
      administrativeOnly: true,
    },
  ],
  escalationKeywords: ["大量流血", "呼吸困难", "抽搐", "失去反应", "晕倒", "严重受伤"],
  restrictedQuestionPatterns: [
    /係咪.*病/u,
    /是不是.*病/u,
    /要唔要.*食药/u,
    /要不要.*吃药/u,
    /点医/u,
    /怎么治/u,
    /可唔可以.*药/u,
  ],
  followUpRules: [
    {
      id: "pet_groom_6w",
      label: "6 周美容提醒",
      trigger: "time_since_service",
      afterDays: 42,
      serviceIds: ["pet_bath", "pet_full_groom"],
      customerMessage: "距离上次美容约 6 周，如需要可以在这里安排下一次护理。",
    },
  ],
  integrationTargets: [],
  defaultHumanApprovalLeadHours: 12,
  metadata: {
    candidate: true,
    notes: ["用于验证通用核心可在不修改核心代码的情况下加载宠物行业语义。", "宠物健康判断与用药建议一律转人工。"],
  },
};
